name: Build LaTeX PDF
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install Python & Pygments
      - name: Set up Python & install Pygments
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install Pygments

      # Compile with shell‑escape
      - name: Compile LaTeX (with minted support)
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          extra_system_packages: "py-pygments"
          args: -pdf -f -file-line-error -interaction=nonstopmode -shell-escape
          latexmk_shell_escape: true
  
      - name: Move PDF into docs/
        run: |
          mkdir -p docs
          mv main.pdf docs/book.pdf

      - name: Commit & Push PDF
        uses: EndBug/add-and-commit@v9
        with:
          message: "Auto‑update book.pdf"
          add: "docs/book.pdf"
