name: Build LaTeX PDF

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub provides Ubuntu for the build environment

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up LaTeX environment
      - name: Set up LaTeX
        uses: dante-ev/setup-texlive-action@v1
        with:
          texlive_version: '2020'  # You can specify which version of TeX Live to use

      # Step 3: Build the PDF
      - name: Build PDF
        run: |
          # Create build directory if it doesn't exist
          mkdir -p build
          # Run pdflatex twice to generate the PDF and resolve references
          pdflatex -output-directory=build main.tex
          pdflatex -output-directory=build main.tex

      # Step 4: Upload the PDF as a build artifact
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: book-pdf
          path: build/book.pdf
      # Step 5: Commit and push the generated PDF to the repository
      - name: Commit and push PDF
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          mv build/book.pdf pdf/book.pdf
          git add pdf/book.pdf
          git commit -m "Update PDF"
          git push
