name: Build LaTeX PDF
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          compiler: pdflatex
          args: -file-line-error -halt-on-error -interaction=nonstopmode

      - name: Move PDF into docs/
        run: |
          mkdir -p docs
          mv main.pdf docs/book.pdf

      - name: Commit & Push PDF
        uses: EndBug/add-and-commit@v9
        with:
          message: "Auto‑update book.pdf"
          add: "docs/book.pdf"
